### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by saipavan10-git** [saipavan10-git/COVID-19-Vaccination-Portal#6]
### Discussed in https://github.com/saipavan10-git/COVID-19-Vaccination-Portal/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **saipavan10-git** January 14, 2022</sup>
All the details about the user stories we came across while talking about this application.</div>

**Comment by mayichong** [comment]
Core User stories:
1. As a user, I want to register and login with my own credentials, so I can easily manage my own account information.
2. As a user, I want to modify my account information (password, email, etc), so I can feel more in control.
3. As a user, I want to check my COVID-19 Vaccine information. 
4. As a user, I want to know what type of vaccine is/are available nearby, so I can make an appointment. 
5. As a user, I want to know when will be the next available date to get the next dose of vaccine.
6. As a user, I want to see all health providers nearby.

Extra (Optional) stories: 
As a user, I want to see COVID-19 Statistics/Data nearby. (bar graph, line graph, total #)
As a user, I want to see the latest COVID-19 News for each state (regulations, changes, etc).
As a user, I want to know if any self-test kit is available nearby/online.

**Comment by saipavan10-git** [comment]
Core User:

1.  As a user, I want to verify my vaccine certificate.
2.   As a user, I want to be able to download my certificate or share it.
3.  As a user, I want to be able to add other members of my family to my account. 

Users stories for healthcare providers perspective :

1. As a user, I want to login to my healthcare profile.
2. As a user, I want to add vaccine batch details.
3.  As a user, I want to open up new slots.
4.  As a user, I want to know how many people got vaccinated that day.

May be some other possible extras :

- As a user, I want to know how many doses are left.
-  As a user, I want to send remainders to get vaccinated.
-  As a user, I want to send info that vaccines are safe.

**Comment by saipavan10-git** [comment]
Although we cannot possibly implement all these issues in Sprint 1. We should be able to identify the ones we can.

**Comment by Vtanneru** [comment]
Core User:

As a user,I Expect a Authorized login with atleast OTP Authentication.
As a user,I need an ease of accesss towards the Vaccination Certificate Details.
As a user,The vaccination certificate should consists of all the Vaccination Details like Doses Taken,Dates at which doses were taken etc.,,
As a user,I expect that the vaccination certificate should have my demographics over the digital Certifiacte.
As a user, I need an graph or some details furnished with the Covid trends at present.
As a user,I expect a emergency covid contact details should be furnished with time to time updated details.

Additional Details;
As a user,I need the Testing location details.
As a user,I want the nearest vaccination center and also a slot booking facility.

**Comment by Klps-1248** [comment]
Core User:
As a user, I want a description of the type of vaccine provided and its particular
(for say, "We provide Moderna, Johnson & Johnson’s Janssen, and Pfizer COVID-19 Vaccines.
Moderna and J&J both vaccines have a minimum age of 18 years and older.
Pfizer vaccine has a minimum age of 12 years and older" )
As a user, I want a demonstration video/animation of the registration that can be useful to just follow along played on the side for reference.
As a user, I want my vaccine certificate linked to my State-ID/Driver license or any other government-approved ID.
As a user, I want the FAQs section to be about COVID-19 Vaccine and Vaccine Registration.

Extra (Optional) stories:
As a user, I want to see the number of vaccinations done regionally with statistics like the way it is on this website[https://ourworldindata.org/covid-vaccinations?country=OWID_WRL](url)
As a user, I expect my vaccine certificate to be mailed to my email, phone number directly to download.
